version: '2'

# IP addresses are explicitly assigned because ircu does not (at
# the current time) handle hostnames for inbound connections, so
# hub.conf will reject connections for a Connect block with
#   host = "leaf-1.testnet_internal";
# in hub.conf.
#
# This is very non-scalable, but IRC is traditionally like that.

services:
  hub:
    container_name: hub
    build:
      context: .
      dockerfile: Dockerfile.ircd
    image: testnet-ircd
    expose: ["7700"]
    ports: ["6669:6667"]
    command: ["-n", "-f", "hub.conf"]
    networks:
      internal:
        ipv4_address: 10.0.0.1
  leaf-1:
    container_name: leaf-1
    image: testnet-ircd
    expose: ["7700"]
    ports: ["6667:6667"]
    links: ["hub"]
    command: ["-n", "-f", "leaf-1.conf"]
    networks:
      internal:
        ipv4_address: 10.0.1.1
  leaf-2:
    container_name: leaf-2
    image: testnet-ircd
    expose: ["7700"]
    ports: ["6668:6667"]
    links: ["hub"]
    command: ["-n", "-f", "leaf-2.conf"]
    networks:
      internal:
        ipv4_address: 10.0.1.2
  srvx:
    container_name: srvx
    build:
      context: .
      dockerfile: Dockerfile.srvx
    image: testnet-srvx
    links: ["hub"]
    networks:
      internal:
        ipv4_address: 10.0.2.1

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.0.0.0/16
         ip_range: 10.0.3.0/24
         gateway: 10.0.0.2
