FROM alpine:3
LABEL Description="Runs an Undernet IRC (ircu2) daemon"

COPY . /tmp
RUN cp /tmp/*.pub /etc/apk/keys \
    && apk add --update -X /tmp/irc \
       ircu2 \
       iauthd-c \
    && rm -rf /var/cache/apk/* /tmp/irc \
    && chown -R coder-com /home/coder-com
WORKDIR /usr/lib
USER coder-com
STOPSIGNAL SIGTERM
ENTRYPOINT ["/usr/bin/ircd"]
CMD ["-n"]
