FROM alpine:3
LABEL Description="Runs a srvx 1.x daemon"

COPY . /tmp
RUN cp /tmp/*.pub /etc/apk/keys \
    && apk add --update -X /tmp/irc \
       srvx \
    && rm -rf /var/cache/apk/* /tmp/irc \
    && chown -R coder-com /home/coder-com
WORKDIR /home/coder-com
USER coder-com
STOPSIGNAL SIGQUIT
ENTRYPOINT ["/usr/srvx"]
CMD ["-f"]
